site_name: TeamReadr
extra_css: [extra.css]
nav:
  - Home: index.md
  - About: about.md
  - Admin-side Guide: admin-guide.md
  - Client-side Guide: client-guide.md
  - Technical Guide: tech.md
theme: readthedocs
markdown_extensions:
  - toc:
      separator: "-"
